version: '3.8'

services:
    app:
        image: php:8.4-fpm
        container_name: bodo_cms_app
        working_dir: /var/www/html/
        volumes:
            - ../:/var/www/html/
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: bodo_cms_web
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www/html/bodo_cms
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: bodo_cms_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laracms
            MYSQL_USER: bodo_user
            MYSQL_PASSWORD: bodo_pass
        ports:
            - "8306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data: